"use client";
import { useEffect, useState } from "react";
type Property = { id:string; name:string; type:string; area:string; annualRent:number; inspectionFee:number; agencyFee:number; cautionFee:number; legalFee:number; total:number };
export default function PropertyPanel({ onUpdate }: { onUpdate:(data:any)=>void }) {
  const [listings,setListings]=useState<Property[]>([]); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState("");
  async function load(){ setLoading(true); try{const r=await fetch("/api/game/property");const d=await r.json();if(!r.ok)setNotice(d.error??"Could not load properties.");else setListings(d.listings??[]);}catch{setNotice("Could not connect to the property market.");}finally{setLoading(false);}}
  useEffect(()=>{void load()},[]);
  async function rent(propertyId:string){setLoading(true);setNotice("");try{const r=await fetch("/api/game/property/rent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({propertyId})});const d=await r.json();if(!r.ok)setNotice(d.error??"Could not complete the move.");else{setNotice(d.message);onUpdate(d);}}catch{setNotice("Could not connect to the property market.");}finally{setLoading(false);}}
  return <div className="space-y-5"><div className="rounded-3xl border border-slate-200 bg-white p-7"><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-600">Abuja Property Market</p><h1 className="mt-2 text-3xl font-black">Find your place.</h1><p className="mt-2 text-sm text-slate-500">Move-in cost includes annual rent, inspection, agency, caution and legal fees.</p>{notice&&<div className="mt-5 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-800">{notice}</div>}{loading&&!listings.length?<p className="mt-6 text-sm text-slate-500">Loading listings...</p>:<div className="mt-6 grid gap-3 md:grid-cols-2">{listings.map(p=><div key={p.id} className="rounded-2xl border border-slate-200 p-5"><p className="font-black">{p.name}</p><p className="mt-1 text-xs font-semibold text-slate-500">{p.area} · {p.type}</p><p className="mt-4 text-xl font-black">₦{p.annualRent.toLocaleString()} <span className="text-xs font-semibold text-slate-400">/ year</span></p><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><span>Inspection ₦{p.inspectionFee.toLocaleString()}</span><span>Agency ₦{p.agencyFee.toLocaleString()}</span><span>Caution ₦{p.cautionFee.toLocaleString()}</span><span>Legal ₦{p.legalFee.toLocaleString()}</span></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-sm font-black">Move-in ₦{p.total.toLocaleString()}</span><button onClick={()=>rent(p.id)} disabled={loading} className="rounded-xl bg-slate-950 px-4 py-3 text-xs font-black text-white">Rent</button></div></div>)}</div>}</div></div>;
}